CREATE DATABASE INVENTARIO;
USE INVENTARIO;

CREATE TABLE IF NOT EXISTS AREA (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NOMBRE ENUM("Administrativa", "Bodega", "Recepción", "Contabilidad", "Técnica")
);

CREATE TABLE IF NOT EXISTS DEPARTAMENTO (
  ID INT AUTO_INCREMENT,
  NOMBRE ENUM("Ventas", "Contabilidad", "Implementación", "Importaciones", "Compras", "Bodega", "RRHH", "RMA", "Desarrollo", "Gerencia", "Recepción", "Diseño Gráfico", "Sala de reunión"),
  AREA INT NOT NULL,
  FOREIGN KEY (AREA) REFERENCES AREA (ID),
  PRIMARY KEY (ID, AREA)
);

CREATE TABLE IF NOT EXISTS EMPLEADO (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NOMBRES VARCHAR(255) NOT NULL,
  APELLIDOS VARCHAR(255) NOT NULL,
  CARGO ENUM("Asistente de Facturación", "Asistente de Cobranzas", "Asistente de Contabilidad", "Asistente de Importaciones", "Bodega", "Compras", "Desarrollador", "Implementador", "Gerente de Operaciones", "Gerente de Ventas", "Gerente General", "Pasante", "Recepcionista", "Supervisor", "Recursos Humanos", "Técnico"),
  DEPARTAMENTO INT,
  AREA INT,
  EXT_TLF INT,
  FOREIGN KEY (DEPARTAMENTO, AREA) REFERENCES DEPARTAMENTO (ID, AREA)
);

CREATE TABLE IF NOT EXISTS TELEFONO (
  CODIGO VARCHAR(255),
  SERIE VARCHAR(255),
  MARCA VARCHAR(255) NOT NULL,
  PRIMARY KEY (CODIGO, SERIE),
  EMPLEADO INT,
  FOREIGN KEY (EMPLEADO) REFERENCES EMPLEADO (ID)
);

CREATE TABLE IF NOT EXISTS MAQUINA (
  CODIGO VARCHAR(255),
  SERIE VARCHAR(255),
  TIPO ENUM("Laptop", "PC"),
  NOMBRE_EQUIPO VARCHAR(255) UNIQUE NOT NULL,
  SISTEMA_OPERATIVO VARCHAR(255) NOT NULL,
  MARCA VARCHAR(255) NOT NULL,
  ESPACIO INT NOT NULL,
  ANTIVIRUS VARCHAR(255),
  FECHA_ADQUISICION DATE,
  USUARIO VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  NOVEDAD VARCHAR(255),
  EMPLEADO INT,
  PRIMARY KEY (CODIGO, SERIE),
  FOREIGN KEY (EMPLEADO) REFERENCES EMPLEADO (ID)
);

CREATE TABLE IF NOT EXISTS IMPRESORA (
  CODIGO VARCHAR(255),
  SERIE VARCHAR(255),
  TIPO ENUM("Láser", "Multifuncional", "Scanner", "De Tarjetas", "Laminador"),
  MARCA VARCHAR(255) NOT NULL,
  MODELO VARCHAR(255) NOT NULL,
  INTERFAZ VARCHAR(255) NOT NULL,
  AREA INT,
  PRIMARY KEY (CODIGO, SERIE),
  SERIE_LAMINADOR VARCHAR(255),
  FOREIGN KEY (AREA) REFERENCES AREA (ID)
);
